# Generated by Django 4.0.5 on 2022-06-22 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название плейлиста')),
                ('description', models.CharField(max_length=500, verbose_name='Описание плейлиста')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название трека')),
                ('author', models.CharField(max_length=256, verbose_name='Автор трека')),
                ('track', models.FileField(upload_to='static/music/')),
            ],
        ),
    ]
